folder_watcher:
  - folder: /tmp
    patterns:
      - '*.mp4'
      
input_boolean:
  outdoor_motion_notify_photo:
    name: Notify on outdoor motion (photo)
    icon: mdi:run-fast

  outdoor_motion_notify_video:
    name: Notify on outdoor motion
    icon: mdi:run-fast

  indoor_motion_notify:
    name: Notify on indoor motion
    icon: mdi:run-fast

binary_sensor:
  - platform: hikvision
    host: 192.168.1.200
    port: 8889
    username: !secret hikvision_username
    password: !secret hikvision_password
    customize:
      saturn_nvr_line_crossing_1:
        delay: 15
      saturn_nvr_line_crossing_2:
        delay: 15
      saturn_nvr_line_crossing_3:
        delay: 15
      saturn_nvr_line_crossing_4:
        delay: 15
      saturn_nvr_line_crossing_5:
        delay: 15

homeassistant:
  customize:
    binary_sensor.saturn_nvr_line_crossing_1:
      friendly_name: Side Passage
    binary_sensor.saturn_nvr_line_crossing_2:
      friendly_name: Kitchen Side
    binary_sensor.saturn_nvr_line_crossing_3:
      friendly_name: Porch Roof
    binary_sensor.saturn_nvr_line_crossing_4:
      friendly_name: Kitchen Roof
    binary_sensor.saturn_nvr_line_crossing_5:
      friendly_name: Back Garden

automation:
  - alias: Indoor intrusion detection
    initial_state: 'on'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: 
          - binary_sensor.av_room_motion
          - binary_sensor.entrance_motion
          - binary_sensor.lounge_motion
          - binary_sensor.landing_motion
          - binary_sensor.staircase_motion
        from: 'off'
        to: 'on' 
    condition:
    - condition: state
      entity_id: input_boolean.indoor_motion_notify
      state: 'on'
    action:
      - service: telegram_bot.send_message
        data_template:
          target:
            - !secret telegram_chat_id_alexey
            - !secret telegram_chat_id_marina
          title: ""
          message: "\U0001F6E1 Movement in {{ trigger.to_state.attributes.friendly_name }}"

  - alias: Capture outdoor movement photo
    initial_state: 'on'
    hide_entity: true
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.saturn_nvr_line_crossing_1
          - binary_sensor.saturn_nvr_line_crossing_2
          - binary_sensor.saturn_nvr_line_crossing_3
          - binary_sensor.saturn_nvr_line_crossing_4
          - binary_sensor.saturn_nvr_line_crossing_5
        from: 'off'
        to: 'on'
    condition:
    - condition: state
      entity_id: input_boolean.outdoor_motion_notify_photo
      state: 'on'
    action:
      - service: telegram_bot.send_photo
        data_template:
          target:
            - !secret telegram_chat_id_alexey
            - !secret telegram_chat_id_marina
          url: "http://localhost:8123{{ states.camera[{
            '1' : 'side_passage',
            '2' : 'kitchen_side',
            '3' : 'porch_roof',
            '4' : 'kitchen_roof',
            '5' : 'back_garden'
          }[trigger.entity_id[-1]]].attributes.entity_picture }}"
          caption: "Movement in {{ trigger.to_state.attributes.friendly_name }}"
          inline_keyboard:
            - "\U0001F4F9 New snapshot:/snapshot {{ {
            '1' : 'side_passage',
            '2' : 'kitchen_side',
            '3' : 'porch_roof',
            '4' : 'kitchen_roof',
            '5' : 'back_garden'
          }[trigger.entity_id[-1]] }}"

  - alias: Capture outdoor movement video
    initial_state: 'on'
    hide_entity: true
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.saturn_nvr_line_crossing_1
          - binary_sensor.saturn_nvr_line_crossing_2
          - binary_sensor.saturn_nvr_line_crossing_3
          - binary_sensor.saturn_nvr_line_crossing_4
          - binary_sensor.saturn_nvr_line_crossing_5
        from: 'off'
        to: 'on'
    condition:
    - condition: state
      entity_id: input_boolean.outdoor_motion_notify_video
      state: 'on'
    action:
      - service: camera.record
        data_template:
          entity_id: "camera.{{ {
            '1' : 'side_passage',
            '2' : 'kitchen_side',
            '3' : 'porch_roof',
            '4' : 'kitchen_roof',
            '5' : 'back_garden'
          }[trigger.entity_id[-1]] }}"
          filename: "/tmp/capture_saturn_{{ as_timestamp(now()) | int }}_{{ trigger.entity_id[-1] }}.mp4"
          lookback: 10
          duration: 30

  - alias: Send outdoor movement video via Telegram
    initial_state: 'on'
    hide_entity: true
    trigger:
      platform: event
      event_type: folder_watcher
      event_data:
        event_type: created
    condition:
      - condition: template
        value_template: "{{ trigger.event.data.file.startswith('capture_saturn_') }}"
    action:
      - delay:
          seconds: 30
      - service: telegram_bot.send_video
        data_template:
          target:
            - !secret telegram_chat_id_alexey
            - !secret telegram_chat_id_marina
          file: "{{ trigger.event.data.path }}"
          caption: "Movement in {{ state_attr('binary_sensor.saturn_nvr_line_crossing_' + trigger.event.data.file[-5:-4], 'friendly_name') }}"