input_boolean:
  presence_simulation:
    name: Presence simulation
    icon: mdi:ghost

script:
  away_lights:
    alias: Away lights
    sequence:
      - delay: '00:02:30'
      - service: light.turn_on
        entity_id: 
          - light.staircase
          - light.lounge_floor_lamp
      - delay: '0{{ range(0,1) | random | int }}:{{ range(30,59) | random | int }}:00'
      - service: light.turn_on
        entity_id: 
          - light.study_wall_lights
          - light.kitchen_island_pendants
      - delay: '0{{ range(3,5) | random | int }}:{{ range(30,59) | random | int }}:00'
      - service: light.turn_off
        entity_id: light.kitchen_island_pendants
    
  away_lights_motion:
    alias: Away lights on motion
    sequence:
      - delay: '00:00:0{{ range(2, 6) | random | int }}' 
      - service: light.turn_on
        entity_id:
          - light.staircase
          - light.master_bedroom_spotlights
      - delay: '00:00:{{ range(10, 15) | random | int }}'  
      - service: light.turn_on
        entity_id:
          - light.hallway_spotlights
          - light.outside
      - delay: '00:0{{ range(3, 9) | random | int }}:00'      
      - service: light.turn_off
        entity_id: 
          - light.staircase
          - light.master_bedroom_spotlights
          - light.hallway_spotlights
          - light.outside

automation:
  - alias: Presense simulation lights on
    initial_state: 'on'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.presence_simulation
        to: 'on'
      - platform: state
        entity_id: 'sun.sun'
        to: 'below_horizon'
    condition:  
      condition: and
      conditions:
        - condition: state
          entity_id: 'sun.sun'
          state: 'below_horizon'
        - condition: time
          before: '23:45:00'
        - condition: state
          entity_id: input_boolean.presence_simulation
          state: 'on'
    action:
      - service: script.turn_on
        entity_id: script.away_lights

  - alias: Presense simulation lights off
    initial_state: 'on'
    hide_entity: true
    trigger:
      platform: time
      at: '23:45:00'
    condition:
      condition: state
      entity_id: input_boolean.presence_simulation
      state: 'on'
    action:
      - service: script.turn_off
        entity_id: script.away_lights
      - service: light.turn_off
        entity_id: 
          - light.staircase
          - light.study_wall_lights
          - light.kitchen_island_pendants
          - light.lounge_floor_lamp

  - alias: Presense simulation off
    initial_state: 'on'
    hide_entity: true
    trigger:
      platform: state
      entity_id: input_boolean.presence_simulation
      to: 'off'
    action:
      - service: script.turn_off
        entity_id: script.away_lights
      - service: light.turn_off
        entity_id: 
          - light.staircase
          - light.study_wall_lights
          - light.kitchen_island_pendants
          - light.lounge_floor_lamp

  - alias: Presence simulation on outdoor motion
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.saturn_nvr_line_crossing_1
          - binary_sensor.saturn_nvr_line_crossing_2
          - binary_sensor.saturn_nvr_line_crossing_3
          - binary_sensor.saturn_nvr_line_crossing_4
          - binary_sensor.saturn_nvr_line_crossing_5
        from: 'off'
        to: 'on'
    condition:  
      condition: and
      conditions:
        - condition: state
          entity_id: 'sun.sun'
          state: 'below_horizon'
        - condition: time
          after: '23:45:00'
        - condition: state
          entity_id: input_boolean.presence_simulation
          state: 'on'
        - condition: state
          entity_id: script.away_lights_motion
          state: 'off'
    action:
      - service: script.turn_on
        entity_id: script.away_lights_motion
