homeassistant:
  customize:
    cover.rear_gate:
      device_class: garage

switch:
  platform: knx
  name: Rear gate relay
  address: 7/7/2

cover:
  platform: template
  covers:
    rear_gate:
      friendly_name: Rear gate
      value_template: "{{ is_state('switch.rear_gate_relay', 'on') }}"
      icon_template: >-
        {% if is_state('switch.rear_gate_relay', 'on') %}
          mdi:garage-open
        {% else %}
          mdi:garage
        {% endif %}
      open_cover:
        service: switch.turn_on
        entity_id: switch.rear_gate_relay
      close_cover:
        service: switch.turn_off
        entity_id: switch.rear_gate_relay

automation:
  - alias: Notify rear gate opening
    initial_state: 'on'
    hide_entity: true
    trigger:
      platform: state
      entity_id: switch.rear_gate_relay
      to: 'on'
    action:
      - service: rest_command.casatunes_tts
        data:
          message: "Rear gate is opening"
      - event: tileboard
        event_data:
          command: "notify"
          id: "rear_gate"
          icon: "mdi-gate"
          type: "info"
          title: "Attention"
          message: "Rear gate is opening"
          lifetime: 20