- alias: Telegram climate
  initial_state: 'on'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: "/climate"
  action:
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: "{{ trigger.event.data.id }}"
        message: ""
    - service: telegram_bot.edit_message
      data_template:
        message_id: "{{ trigger.event.data.message.message_id }}"
        chat_id: "{{ trigger.event.data.chat_id }}"
        message: >
          {{ "\U00002744" }} Climate summary
        

          {% set icons = {
            'clear-day' :  '\U00002600', 
            'clear-night' : '\U0001F319', 
            'cloudy' : '\U00002601', 
            'rain': '\U0001F327', 
            'sleet' : '\U0001F328', 
            'snow' : '\U0001F328', 
            'wind' : '\U0001F32C', 
            'fog' : '\U0001F32B', 
            'partly-cloudy-day' : '\U0001F325', 
            'partly-cloudy-night' : '\U0001F325' 
          } %}
          {{ icons[states.sensor.dark_sky_icon.state] if states.sensor.dark_sky_icon.state in icons else '\U00002601' }} *{{ states('sensor.dark_sky_temperature') }} °C* {{ states('sensor.dark_sky_summary') }}

        
          {{ "\U0001F4A7" }} {{ states('sensor.dark_sky_humidity') }}%   {{ "\U0001F32C" }} {{ states('sensor.dark_sky_wind_speed') }} m/s

          {{ "\U0000202F" * 74 }}{{ "\U0000FEFF" }}        

          *- Outside* {{ states('sensor.outside_temperature') }} °C
        
          *- Downstairs* {{ states('sensor.downstairs_temperature') }} °C
        
          *- Upstairs* {{ states('sensor.upstairs_temperature') }} °C

        
          *Hot water* is {{ states('switch.hot_water') }} _({{  relative_time(states.switch.hot_water.last_changed) }})_
        
          *Towel rails* are {{ states('switch.towel_rails') }} _({{  relative_time(states.switch.towel_rails.last_changed) }})_


          *Climate mode* {{ states('input_select.climate_mode') }}
        inline_keyboard:
          - "\U0001F504 Reload:/climate"
          - "\U0001F6CB Rooms:/climate_rooms, \U00002744 Climate mode:/climate_mode"
          - "\U0001F3E0 Main menu:/menu_callback"

- alias: Telegram climate summary
  initial_state: 'on'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: "/climate_rooms"
  action:
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: "{{ trigger.event.data.id }}"
        message: ""
    - service: telegram_bot.edit_message
      data_template:
        message_id: "{{ trigger.event.data.message.message_id }}"
        chat_id: "{{ trigger.event.data.chat_id }}"
        message: >-
          {{ "\U00002744" }} Rooms climate summary

          {{"\U0000202F" * 74}}{{"\U0000FEFF"}}
          {% set floors = {
            'Downstairs': {
              'Hallway' : 'hallway', 
              'AV Room' : 'av_room', 
              'Lounge' : 'lounge',
              'Dining Room' : 'dining_room',
              'Kitchen' : 'kitchen',
              'Utility Room': 'utility_room',
            },
            'Upstairs': {
              'Landing' : 'landing',
              'Master Bedroom' : 'master_bedroom',
              'Master Bathroom' : 'master_bathroom',
              'Kids Room' : 'kids_room',
              'Study' : 'study',
              'Guest room' : 'guest_room',
              'Bathroom': 'bathroom'
            }
          } %}
          {% for floor, rooms in floors.items() %}

          *{{ floor }}*


          {% for k, v in rooms.items(): %}
          *- {{ k }}* {{ states.climate[v].attributes.current_temperature }} °C  _({{ states.climate[v].state }})_

          {% endfor %}
          {% endfor %}
        inline_keyboard:
          - "\U0001F504 Reload:/climate_rooms"
          - "\U000021A9 Back:/climate, \U0001F3E0 Main menu:/menu_callback"

- alias: Telegram climate mode
  initial_state: 'on'
  hide_entity: true
  trigger:
    - platform: event
      event_type: telegram_callback
      event_data:
        data: "/climate_mode"
  action:
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: "{{ trigger.event.data.id }}"
        message: ""
    - service: telegram_bot.edit_message
      data_template:
        message_id: "{{ trigger.event.data.message.message_id }}"
        chat_id: "{{ trigger.event.data.chat_id }}"
        message: >-
          {{ "\U00002744" }} Choose climate mode

          {{ "\U0000202F" * 74 }}{{ "\U0000FEFF" }} 
        inline_keyboard:
          - "\U0001F504 Reload:/climate_mode"
          - "{% if is_state('input_select.climate_mode', 'Comfort') %}\U00002611 {% endif %}Comfort:/set_climate_mode Comfort, {% if is_state('input_select.climate_mode', 'Away') %}\U00002611 {% endif %}Away:/set_climate_mode Away"
          - "{% if is_state('input_select.climate_mode', 'Sleep') %}\U00002611 {% endif %}Sleep:/set_climate_mode Sleep, {% if is_state('input_select.climate_mode', 'Eco') %}\U00002611 {% endif %}Eco:/set_climate_mode Eco"
          - "\U000021A9 Back:/climate, \U0001F3E0 Main menu:/menu_callback"

- alias: Telegram climate mode setting
  initial_state: 'on'
  hide_entity: true
  trigger:
    - platform: event
      event_type: telegram_callback
  condition:
    - condition: template
      value_template: "{{ trigger.event.data.data.startswith('/set_climate_mode ') }}"
  action:
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: "{{ trigger.event.data.id }}"
        message: ""
    - service: input_select.select_option
      data_template:
        entity_id: input_select.climate_mode
        option: "{{ trigger.event.data.data.split(' ', 1)[1] }}"
    - service: telegram_bot.edit_message
      data_template:
        message_id: "{{ trigger.event.data.message.message_id }}"
        chat_id: "{{ trigger.event.data.chat_id }}"
        message: >-
          {{ "\U00002744" }} Choose climate mode

          {{ "\U0000202F" * 74 }}{{ "\U0000FEFF" }} 
        inline_keyboard:
          - "\U0001F504 Reload:/climate_mode"
          - "{% if is_state('input_select.climate_mode', 'Comfort') %}\U00002611 {% endif %}Comfort:/set_climate_mode Comfort, {% if is_state('input_select.climate_mode', 'Away') %}\U00002611 {% endif %}Away:/set_climate_mode Away"
          - "{% if is_state('input_select.climate_mode', 'Sleep') %}\U00002611 {% endif %}Sleep:/set_climate_mode Sleep, {% if is_state('input_select.climate_mode', 'Eco') %}\U00002611 {% endif %}Eco:/set_climate_mode Eco"
          - "\U000021A9 Back:/climate, \U0001F3E0 Main menu:/menu_callback"