homeassistant:
  customize:
    switch.boiler_room_extractor_fan:
      icon: mdi:fan

light:
  - platform: knx   
    name: Boiler room pendant 
    address: 1/1/49
    state_address: 1/2/49
    
  - platform: knx 
    name: Boiler room wall light 
    address: 1/1/50
    state_address: 1/2/50

switch:
  - platform: knx   
    name: Boiler room extractor fan 
    address: 7/1/8