homeassistant:
  customize:
    switch.toilet_extractor_fan:
      icon: mdi:fan

light:
  - platform: knx   
    name: Toilet spotlight 
    address: 1/1/41
    state_address: 1/2/41

switch:
  - platform: knx  
    name: Toilet extractor fan 
    address: 7/1/6

automation:
  - alias: Toilet light on
    initial_state: 'on'
    hide_entity: true
    trigger:
      platform: state
      entity_id: binary_sensor.toilet_motion
      from: 'off'
      to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: 'sun.sun'
          state: 'below_horizon'
        - condition: numeric_state
          entity_id: sensor.toilet_illumination
          below: 10
    action:
      service: light.turn_on
      entity_id: light.toilet_spotlight
  
  - alias: Toilet light off
    initial_state: 'on'
    hide_entity: true
    trigger:
      platform: state
      entity_id: binary_sensor.toilet_motion
      from: 'on'
      to: 'off'
      for:
        minutes: 2
    action:
      service: light.turn_off
      entity_id: light.toilet_spotlight