hue:
  bridges:
    - host: 192.168.2.60
      allow_hue_groups: false 

input_boolean:
  neptune_presence_simulation:
    name: Presence simulation
    icon: mdi:ghost

script:
  neptune_away_lights:
    alias: Neptune away lights
    sequence:
      - delay: '00:02:30'
      - service: light.turn_on
        entity_id: light.neptune_lounge
      - delay: '0{{ range(0,1) | random | int }}:{{ range(30,59) | random | int }}:00'
      - service: light.turn_on
        entity_id: 
          - light.neptune_guest_room
          - light.neptune_small_guest_room
      - delay: '0{{ range(3,5) | random | int }}:{{ range(30,59) | random | int }}:00'
      - service: light.turn_off
        entity_id: light.neptune_lounge

  neptune_away_lights_motion:
    alias: Neptune away lights on motion
    sequence:
      - delay: '00:00:0{{ range(2, 8) | random | int }}'  
      - service: light.turn_on
        entity_id:
          - light.neptune_guest_room
          - light.neptune_small_guest_room
      - delay: '00:00:{{ range(10, 15) | random | int }}'  
      - service: light.turn_on
        entity_id: light.neptune_lounge
      - delay: '00:0{{ range(2, 8) | random | int }}:00'    
      - service: light.turn_off
        entity_id: 
          - light.neptune_guest_room
          - light.neptune_small_guest_room
          - light.neptune_lounge

automation:
  - alias: Neptune presense simulation lights on
    initial_state: 'on'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.neptune_presence_simulation
        to: 'on'
      - platform: state
        entity_id: 'sun.sun'
        to: 'below_horizon'
    condition:  
      condition: and
      conditions:
        - condition: state
          entity_id: 'sun.sun'
          state: 'below_horizon'
        - condition: time
          before: '23:45:00'
        - condition: state
          entity_id: input_boolean.neptune_presence_simulation
          state: 'on'
    action:
      - service: script.turn_on
        entity_id: script.neptune_away_lights

  - alias: Neptune presense simulation lights off
    initial_state: 'on'
    hide_entity: true
    trigger:
      platform: time
      at: '23:45:00'
    condition:
      condition: state
      entity_id: input_boolean.neptune_presence_simulation
      state: 'on'
    action:
      - service: script.turn_off
        entity_id: script.neptune_away_lights
      - service: light.turn_off
        entity_id: 
          - light.neptune_lounge
          - light.neptune_guest_room
          - light.neptune_small_guest_room

  - alias: Neptune presense simulation off
    initial_state: 'on'
    hide_entity: true
    trigger:
      platform: state
      entity_id: input_boolean.neptune_presence_simulation
      to: 'off'
    action:
      - service: script.turn_off
        entity_id: script.neptune_away_lights
      - service: light.turn_off
        entity_id: 
          - light.neptune_lounge
          - light.neptune_guest_room
          - light.neptune_small_guest_room

  - alias: Neptune presence simulation on outdoor motion
    initial_state: 'on'
    hide_entity: true
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.neptune_nvr_line_crossing_1
          - binary_sensor.neptune_nvr_line_crossing_2
          - binary_sensor.neptune_nvr_line_crossing_3
          - binary_sensor.neptune_nvr_line_crossing_4
          - binary_sensor.neptune_nvr_line_crossing_5
        from: 'off'
        to: 'on'
    condition:  
      condition: and
      conditions:
        - condition: state
          entity_id: 'sun.sun'
          state: 'below_horizon'
        - condition: time
          after: '23:45:00'
        - condition: state
          entity_id: input_boolean.neptune_presence_simulation
          state: 'on'
        - condition: state
          entity_id: script.neptune_away_lights_motion
          state: 'off'
    action:
      - service: script.turn_on
        entity_id: script.neptune_away_lights_motion
